[logger]
level = "INFO"
path = "./calendar.log"

[db]
inMemory = false
host = "postgres"
port = 5432
username = "postgres"
password = "123456"
dbname = "calendar"

[http]
host = "localhost"
port = 8081